ALTER TABLE users
ADD COLUMN description TEXT NULL,
ADD COLUMN website VARCHAR(255) NULL,
ADD COLUMN social_vk VARCHAR(255) NULL,
ADD COLUMN social_rutube VARCHAR(255) NULL,
ADD COLUMN profile_image VARCHAR(255) NULL; 